name: calendario_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  data_table_2: ^2.5.12
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  expandable_page_view: ^1.0.17
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.0
  flexible_grid_view: ^0.0.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic_plus: ^3.3.0
  image_stack: ^2.1.1
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
